// packages/integrations/vue/src/Editor.tsx
import type { Crepe } from '@milkdown/crepe'
import type { Editor } from '@milkdown/core'
import type { InjectionKey, Ref } from 'vue'
import {
  Fragment,
  defineComponent,
  h,
  provide,
  ref,
} from 'vue'

import type { EditorInfoCtx, GetEditor } from './types'
import { useGetEditor } from './useGetEditor'

h
Fragment

export const editorInfoCtxKey: InjectionKey<EditorInfoCtx> = Symbol('editorInfoCtxKey')

export const Milkdown = defineComponent({
  name: 'Milkdown',
  setup: () => {
    const domRef = useGetEditor()

    return () => h('div', {
      'data-milkdown-root': true,
      ref: domRef,
    })
  },
})

export const MilkdownProvider = defineComponent({
  name: 'MilkdownProvider',
  setup: (_, { slots }) => {
    const dom = ref<HTMLDivElement | null>(null)
    const editorFactory = ref<GetEditor | undefined>(undefined)
    const editor = ref<Editor | undefined>(undefined) as Ref<Editor | undefined>
    const crepe = ref<Crepe | undefined>(undefined) as Ref<Crepe | undefined>
    const loading = ref(true)

    provide(editorInfoCtxKey, {
      loading,
      dom,
      editor,
      editorFactory,
      crepe,
    })

    return () => slots.default?.()
  },
})

// packages/integrations/react/src/Editor.tsx
import type { Crepe } from '@milkdown/crepe'
import type { Editor } from '@milkdown/core'
import type { FC, ReactNode } from 'react'
import React, { useMemo, useRef, useState } from 'react'

import type { EditorInfoCtx, GetEditor } from './types'
import { editorInfoContext, useGetEditor } from './useGetEditor'

export const Milkdown: FC = () => {
  const domRef = useGetEditor()

  return <div data-milkdown-root ref={domRef} />
}

export const MilkdownProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const dom = useRef<HTMLDivElement | undefined>(undefined)
  const [editorFactory, setEditorFactory] = useState<GetEditor | undefined>(undefined)
  const editor = useRef<Editor>()
  const crepe = useRef<Crepe>()
  const [loading, setLoading] = useState(true)

  const editorInfoCtx = useMemo<EditorInfoCtx>(() => ({
    loading,
    dom,
    editor,
    crepe,
    setLoading,
    editorFactory,
    setEditorFactory,
  }), [loading, editorFactory])

  return (
    <editorInfoContext.Provider value={editorInfoCtx}>
      {children}
    </editorInfoContext.Provider>
  )
}
