// packages/vue/src/Editor.tsx
/* Copyright 2021, Milkdown by Mirone. */
import {
    ComponentInternalInstance,
    DefineComponent,
    defineComponent,
    effect,
    getCurrentInstance,
    h,
    InjectionKey,
    markRaw,
    onBeforeMount,
    onUnmounted,
    provide,
    ref,
    shallowReactive,
} from 'vue';

import { EditorComponent, EditorRef } from './EditorComponent';
import { EditorInfo, EditorInfoCtx } from './types';
import { rendererKey } from './useGetEditor';
import { createVueView } from './VueNodeView';

export const editorInfoCtxKey: InjectionKey<EditorInfoCtx> = Symbol();

const refDeprecatedInfo = `
@milkdown/vue:
Passing ref to VueEditor will soon be deprecated, please use:

const { editor, getInstance, getDom, loading } = useEditor(/* creator */);

effect(() => {
    if (!loading) {
        const editor = getInstance();
        const rootDOM = getDom();
    }
})

<VueEditor editor={editor} />
`;

const compositionDeprecatedInfo = `
@milkdown/vue:
Passing editor directly to VueEditor will soon be deprecated, please use:

const { editor } = useEditor(/* creator */);

<VueEditor editor={editor} />
`;

type PortalPair = [key: string, component: DefineComponent];
export const VueEditor = defineComponent<{ editor: EditorInfo; editorRef?: EditorRef }>({
    name: 'milkdown-vue-root',
    setup: (props) => {
        const portals = shallowReactive<PortalPair[]>([]);

        const instance = getCurrentInstance();

        const rootInstance = ref<null | ComponentInternalInstance>(null);

        onBeforeMount(() => {
            rootInstance.value = (instance as ComponentInternalInstance & { ctx: { _: ComponentInternalInstance } }).ctx
                ._ as ComponentInternalInstance;
        });

        onUnmounted(() => {
            rootInstance.value = null;
        });

        const addPortal = markRaw((component: DefineComponent, key: string) => {
            portals.push([key, component]);
        });
        const removePortalByKey = markRaw((key: string) => {
            const index = portals.findIndex((p) => p[0] === key);
            portals.splice(index, 1);
        });
        const renderVue = createVueView(rootInstance, addPortal, removePortalByKey);

        provide(rendererKey, renderVue);

        const usingDeprecatedCompositionAPI = Object.hasOwnProperty.call(props.editor, 'getInstance');

        const { getEditorCallback, dom, editor, loading } = usingDeprecatedCompositionAPI
            ? // @ts-expect-error deprecated old composition API
              (props.editor.editor as EditorInfo)
            : props.editor;

        effect(() => {
            if (usingDeprecatedCompositionAPI) {
                console.warn(compositionDeprecatedInfo);
            }
            if (props.editorRef) {
                console.warn(refDeprecatedInfo);
            }
        });

        provide(editorInfoCtxKey, {
            dom,
            editor,
            loading,
        });

        return () => {
            const portalElements = portals.map(([id, P]) => <P key={id} />);
            return (
                <EditorComponent editorRef={props.editorRef} editor={getEditorCallback.value}>
                    {portalElements}
                </EditorComponent>
            );
        };
    },
});
VueEditor['props'] = ['editor', 'editorRef'];

// packages/react/src/Editor.tsx
/* Copyright 2021, Milkdown by Mirone. */
import { Mark, Node } from '@milkdown/prose/model';
import { forwardRef, useCallback, useEffect, useMemo, useState } from 'react';

import { EditorComponent } from './EditorComponent';
import { portalContext } from './Portals';
import { createReactView } from './ReactNodeView';
import { EditorInfo, EditorInfoCtx, EditorRef, RenderReact } from './types';
import { editorInfoContext } from './useGetEditor';

type EditorProps = {
    editor: EditorInfo;
};

const refDeprecatedInfo = `
@milkdown/react:
Passing ref to ReactEditor will soon be deprecated, please use:

const { editor, getInstance, getDom, loading } = useEditor(/* creator */);

useEffect(() => {
    if (!loading) {
        const editor = getInstance();
        const rootDOM = getDom();
    }
}, [getInstance])

<ReactEditor editor={editor} />
`;

const hooksDeprecatedInfo = `
@milkdown/react:
Passing editor directly to ReactEditor will soon be deprecated, please use:

const { editor } = useEditor(/* creator */);

<ReactEditor editor={editor} />
`;

export const ReactEditor = forwardRef<EditorRef, EditorProps>(({ editor: editorInfo }, ref) => {
    const [portals, setPortals] = useState<React.ReactPortal[]>([]);
    const addPortal = useCallback((portal: React.ReactPortal) => {
        setPortals((ps) => [...ps, portal]);
    }, []);
    const removePortalByKey = useCallback((key: string) => {
        setPortals((x) => {
            const index = x.findIndex((p) => p.key === key);

            return [...x.slice(0, index), ...x.slice(index + 1)];
        });
    }, []);
    const renderReact: RenderReact<Node | Mark> = useCallback(
        (Component, options) => createReactView(addPortal, removePortalByKey)(Component, options),
        [addPortal, removePortalByKey],
    );

    const usingDeprecatedHooksAPI = Object.hasOwnProperty.call(editorInfo, 'getInstance');

    const { getEditorCallback, dom, editor, setLoading } = usingDeprecatedHooksAPI
        ? // @ts-expect-error deprecated old hooks API
          (editorInfo.editor as EditorInfo)
        : editorInfo;

    useEffect(() => {
        if (usingDeprecatedHooksAPI) {
            console.warn(hooksDeprecatedInfo);
        }
        if (ref) {
            console.warn(refDeprecatedInfo);
        }
    }, [ref, usingDeprecatedHooksAPI]);

    const ctx = useMemo<EditorInfoCtx>(() => {
        return {
            dom,
            editor,
            setLoading,
        };
    }, [dom, editor, setLoading]);

    return (
        <editorInfoContext.Provider value={ctx}>
            <portalContext.Provider value={renderReact}>
                {portals}
                <EditorComponent ref={ref} editor={getEditorCallback} />
            </portalContext.Provider>
        </editorInfoContext.Provider>
    );
});
