// packages/vue/src/EditorComponent.tsx
/* Copyright 2021, Milkdown by Mirone. */
import type { Editor } from '@milkdown/core'
import { defineComponent, h, inject } from 'vue'

import { editorInfoCtxKey } from './Editor'
import type { EditorInfoCtx, GetEditor } from './types'
import { useGetEditor } from './useGetEditor'

export const EditorComponent = defineComponent<{ editor: GetEditor; editorRef?: EditorRef }>({
  name: 'milkdown-dom-root',
  setup: (props, { slots }) => {
    useGetEditor(props.editor)
    const ctx = inject(editorInfoCtxKey, {} as EditorInfoCtx)

    if (props.editorRef) {
      props.editorRef.get = () => ctx.editor.value
      props.editorRef.dom = () => ctx.dom.value
    }

    return () => <div ref={ctx.dom}>{slots.default?.()}</div>
  },
})
EditorComponent.props = ['editor', 'editorRef']

export interface EditorRef { get: () => Editor | undefined; dom: () => HTMLDivElement | null }

// packages/react/src/EditorComponent.tsx
/* Copyright 2021, Milkdown by Mirone. */
import { forwardRef, useContext, useImperativeHandle } from 'react';

import { EditorRef, GetEditor } from './types';
import { editorInfoContext, useGetEditor } from './useGetEditor';

export const useGetter = () => {
    const ctx = useContext(editorInfoContext);
    return {
        get: () => {
            return ctx.editor.current;
        },
        dom: () => {
            return ctx.dom.current;
        },
    };
};

export const EditorComponent = forwardRef<EditorRef, { editor: GetEditor }>(({ editor }, ref) => {
    const ctx = useContext(editorInfoContext);
    const getter = useGetter();
    useGetEditor(editor);

    useImperativeHandle(ref, () => getter);
    return <div ref={ctx.dom} />;
});
