// packages/react/src/Portals.tsx
/* Copyright 2021, Milkdown by Mirone. */
import { ViewFactory } from '@milkdown/prose';
import React from 'react';

export const portalContext = React.createContext<(Component: React.FC) => ViewFactory>(() => () => {
    throw new Error();
});

const getId = (portals: React.ReactPortal[]) => portals.map((x) => x.key).join(',');
export const Portals: React.FC<{ portals: React.ReactPortal[] }> = React.memo(
    ({ portals }) => {
        return <>{...portals}</>;
    },
    (prev, next) => {
        return getId(prev.portals) === getId(next.portals);
    },
);

// packages/vue/src/Portals.tsx
/* Copyright 2021, Milkdown by Mirone. */
import { DefineComponent, defineComponent, Fragment, h, nextTick, ref, shallowRef, watch } from 'vue';
export type PortalPair = [key: string, component: DefineComponent];

const getId = (pairs: PortalPair[]) => pairs.map((p) => p[0]).join('\n');

export const Portals = defineComponent((props: { portals: PortalPair[] }) => {
    const portalComponents = shallowRef<Array<DefineComponent>>([]);
    const prev = ref<string>('');
    const renderList = shallowRef<() => JSX.Element[]>(() => []);

    watch(
        () => getId(props.portals),
        (ids) => {
            if (ids !== prev.value) {
                prev.value = ids;
                const next = props.portals.map((p) => p[1]);
                portalComponents.value = next;
            }
        },
    );

    nextTick(() => {
        renderList.value = () => portalComponents.value.map((P) => <P />);
    });

    return () => {
        return <>{renderList.value()}</>;
    };
});
Portals.props = ['portals'];
