// examples/vue/Milkdown.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { VueEditor, useEditor } from '@milkdown/vue';
import { Node } from '@milkdown/prose/model';

export default defineComponent({
    name: 'Milkdown',
    components: {
        VueEditor,
    },
});
</script>
<script lang="ts" setup>
import { effect, ref } from 'vue';
import { Editor, rootCtx, defaultValueCtx, editorCtx } from '@milkdown/core';
import { nord } from '@milkdown/theme-nord';
import { codeFence as cmCodeFence, commonmark } from '@milkdown/preset-commonmark';
import { emoji } from '@milkdown/plugin-emoji';
import { prism } from '@milkdown/plugin-prism';
import { menu } from '@milkdown/plugin-menu';
import { listener, listenerCtx } from '@milkdown/plugin-listener';
import { codeFence } from './CodeFence/CodeFence';
import CodeFence from './CodeFence/CodeFence.vue';

const editorRef = ref<Editor | null>(null);
const mounted = ref(false);

effect(() => {
    if (mounted.value && editorRef.value) {
        mounted.value = true;
        editorRef.value.action((ctx) => {
            ctx;
            // console.log(ctx.get(editorStateCtx).doc);
            // your action here
        });
    }
});

const value = `
# Milkdown 💖 Vue
\`\`\`typescript [Source]
const foo = 'bar';
\`\`\`
`;

const { editor, loading, getInstance, getDom } = useEditor((root, renderVue) =>
    Editor.make()
        .config((ctx) => {
            ctx.set(rootCtx, root);
            ctx.set(defaultValueCtx, value);
            ctx.get(listenerCtx)
                .mounted((ctx) => {
                    editorRef.value = ctx.get(editorCtx);
                    mounted.value = true;
                })
                .markdownUpdated((_, markdown) => {
                    console.log(markdown);
                });
        })
        .use(nord)
        .use(emoji)
        .use(commonmark.replace(cmCodeFence, codeFence(renderVue<Node>(CodeFence))()))
        .use(prism)
        .use(menu)
        .use(listener),
);

effect(() => {
    if (!loading.value) {
        getInstance()?.action((ctx) => {
            ctx;
            console.log(getDom());
        });
    }
});
</script>

<template>
    <VueEditor :editor="editor" />
</template>

// examples/react17/component/milkdown/index.tsx
/* Copyright 2021, Milkdown by Mirone. */

import { defaultValueCtx, Editor, rootCtx } from '@milkdown/core';
import { listener, listenerCtx } from '@milkdown/plugin-listener';
import { prism } from '@milkdown/plugin-prism';
import { tooltip } from '@milkdown/plugin-tooltip';
import { codeFence as cmCodeFence, commonmark, image } from '@milkdown/preset-commonmark';
import { Node } from '@milkdown/prose/model';
import { ReactEditor, useEditor } from '@milkdown/react';
import { nord } from '@milkdown/theme-nord';
import { FC, useEffect } from 'react';

import { CodeFence } from './CodeFence';
import { codeFence } from './CodeFence/codeFence.node';
import { Image } from './Image';

export const Milkdown: FC<{ value: string }> = ({ value }) => {
    const { editor, loading, getInstance } = useEditor((root, renderReact) => {
        const nodes = commonmark
            .configure(image, { view: renderReact(Image) })
            .replace(cmCodeFence, codeFence(renderReact<Node>(CodeFence, { as: 'section' }))());
        return Editor.make()
            .config((ctx) => {
                ctx.set(rootCtx, root);
                ctx.set(defaultValueCtx, value);
                ctx.get(listenerCtx).markdownUpdated((_, value) => {
                    value;
                    // console.log(value);
                });
            })
            .use(nord)
            .use(nodes)
            .use(tooltip)
            .use(prism)
            .use(listener);
    });

    useEffect(() => {
        if (!loading) {
            const instance = getInstance();
            instance?.action((ctx) => {
                ctx;
                // do something
            });
        }
    }, [getInstance, loading]);

    return <ReactEditor editor={editor} />;
};
