// examples/vue/CodeFence/CodeFence.vue
<script lang="ts">
import { defineComponent } from 'vue'
import { useNodeCtx } from '@milkdown/vue'
import type { Node } from '@milkdown/prose/model'
import { languageListSlice } from './CodeFence'

export default defineComponent({
  name: 'CodeFence',
})
</script>

<script setup lang="ts">
const metadata = useNodeCtx<Node>()
const attrs = metadata.node.value.attrs
const languages = metadata.ctx.get(languageListSlice) ?? []

const filename = attrs.filename ?? ''
const lang = attrs.language ?? ''

const showInput = attrs.showInput ?? false

const onChange = (e: Event) => {
  const view = metadata.view
  const node = metadata.node
  const getPos = metadata.getPos
  const { target } = e
  if (!(target instanceof HTMLSelectElement))
    return

  const { value } = target
  if (!view.editable) {
    target.value = node.value.attrs.language
    return
  }
  const { tr } = view.state
  view.dispatch(
    tr.setNodeMarkup(getPos(), undefined, {
      ...node.value.attrs,
      language: value,
    }),
  )
}

const toggleInput = () => {
  const view = metadata.view
  const node = metadata.node
  const getPos = metadata.getPos
  if (!view.editable)
    return

  const show = node.value.attrs.showInput
  const { tr } = view.state
  view.dispatch(
    tr.setNodeMarkup(getPos(), undefined, {
      ...node.value.attrs,
      showInput: !show,
    }),
  )
}

const onKeydown = (e: KeyboardEvent) => {
  e.stopPropagation()
}

const onFilenameChange = (e: Event) => {
  const view = metadata.view
  const node = metadata.node
  const getPos = metadata.getPos

  const { target } = e
  if (!(target instanceof HTMLInputElement))
    return
  if (!view.editable)
    return

  const { value } = target

  const { tr } = view.state
  view.dispatch(
    tr.setNodeMarkup(getPos(), undefined, {
      ...node.value.attrs,
      filename: value,
      showInput: false,
    }),
  )
}
</script>

<template>
  <div class="code-fence">
    <div class="control">
      <span class="filename">
        {{ filename || 'No File Name' }}
        <input v-if="showInput" @keydown="onKeydown" @change="onFilenameChange">
        <button v-else @click="toggleInput">edit</button>
      </span>
      <select @change="onChange">
        <option v-for="language in languages" :key="language" :selected="language === lang" :value="language">
          {{ language }}
        </option>
      </select>
    </div>
    <div class="code">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.code-fence {
    border: 1px solid #ccc;
    padding: 10px;
}

.control {
    margin-bottom: 10px;
    display: flex;
    justify-content: space-between;
}

.code {
    background: #ccc;
    margin: 0 auto !important;
    white-space: pre;
    border-radius: 4px;
    padding: 10px;
}
</style>

// examples/react/component/milkdown/CodeFence/index.tsx
/* Copyright 2021, Milkdown by Mirone. */
import type { Node } from '@milkdown/prose/model'
import { useNodeCtx } from '@milkdown/react'
import type { FC, ReactNode } from 'react'
import { useState } from 'react'

import { languageListSlice } from './codeFence.node'

export const CodeFence: FC<{ children: ReactNode }> = ({ children }) => {
  const { node, ctx, view, getPos } = useNodeCtx<Node>()
  const showInput = node.attrs.showInput
  const filename = node.attrs.filename
  const language = ctx.get(languageListSlice)

  const [input, setInput] = useState('')

  return (
    <div className="code-fence" style={{ border: '1px solid #ccc', padding: 10 }}>
      <div className="control" style={{ marginBottom: 10, display: 'flex', justifyContent: 'space-between' }}>
        <span className="filename">
          <span style={{ marginRight: 10 }}>{filename || 'No File Name'}</span>
          {showInput
            ? (
              <>
                <input
                                onChange={(e) => {
                                  const { target } = e
                                  if (!(target instanceof HTMLInputElement))
                                    return
                                  if (!view.editable)
                                    return

                                  setInput(target.value)
                                }}
                            />
                <button
                                onClick={() => {
                                  const { tr } = view.state

                                  view.dispatch(
                                    tr.setNodeMarkup(getPos(), undefined, {
                                      ...node.attrs,
                                      filename: input,
                                      showInput: false,
                                    }),
                                  )
                                }}
                            >
                  OK
                </button>
              </>
              )
            : (
              <button
                            onClick={() => {
                              if (!view.editable)
                                return

                              const show = node.attrs.showInput
                              const { tr } = view.state
                              view.dispatch(
                                tr.setNodeMarkup(getPos(), undefined, {
                                  ...node.attrs,
                                  showInput: !show,
                                }),
                              )
                            }}
                        >
                edit
              </button>
              )}
        </span>
        <select
                    defaultValue={node.attrs.language}
                    onChange={(event) => {
                      const { target } = event
                      if (!(target instanceof HTMLSelectElement) || !view || !node)
                        return

                      const { value } = target
                      if (!view.editable) {
                        target.value = node.attrs.language
                        return
                      }
                      const { tr } = view.state
                      view.dispatch(
                        tr.setNodeMarkup(getPos(), undefined, {
                          ...node.attrs,
                          language: value,
                        }),
                      )
                    }}
                >
          {language.map(lang => (
            <option key={lang} value={lang}>
              {lang}
            </option>
          ))}
        </select>
      </div>
      <div
                className="code"
                style={{ background: '#ccc', margin: '0 auto', whiteSpace: 'pre', borderRadius: 4, padding: 10 }}
            >
        {children}
      </div>
    </div>
  )
}
